// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeguimientoEnCasa.App.Persistencia;

namespace SeguimientoEnCasa.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SeguimientoEnCasa.App.Dominio.Historico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<int?>("SugerenciaEstudioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("SugerenciaEstudioId");

                    b.ToTable("Historicos");
                });

            modelBuilder.Entity("SeguimientoEnCasa.App.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("SeguimientoEnCasa.App.Dominio.SugerenciaEstudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SugerenciaEstudios");
                });

            modelBuilder.Entity("SeguimientoEnCasa.App.Dominio.Acudiente", b =>
                {
                    b.HasBaseType("SeguimientoEnCasa.App.Dominio.Persona");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int")
                        .HasColumnName("Acudiente_EstudianteId");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasIndex("EstudianteId");

                    b.HasDiscriminator().HasValue("Acudiente");
                });

            modelBuilder.Entity("SeguimientoEnCasa.App.Dominio.Estudiante", b =>
                {
                    b.HasBaseType("SeguimientoEnCasa.App.Dominio.Persona");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaDeNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<float>("Latitud")
                        .HasColumnType("real");

                    b.Property<float>("Longitud")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("SeguimientoEnCasa.App.Dominio.Maestro", b =>
                {
                    b.HasBaseType("SeguimientoEnCasa.App.Dominio.Persona");

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<string>("Registro")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("EstudianteId");

                    b.HasDiscriminator().HasValue("Maestro");
                });

            modelBuilder.Entity("SeguimientoEnCasa.App.Dominio.Tutor", b =>
                {
                    b.HasBaseType("SeguimientoEnCasa.App.Dominio.Persona");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int")
                        .HasColumnName("Tutor_EstudianteId");

                    b.Property<int>("HorasLaborales")
                        .HasColumnType("int");

                    b.Property<string>("TarjetaProfesional")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasIndex("EstudianteId");

                    b.HasDiscriminator().HasValue("Tutor");
                });

            modelBuilder.Entity("SeguimientoEnCasa.App.Dominio.Historico", b =>
                {
                    b.HasOne("SeguimientoEnCasa.App.Dominio.Estudiante", null)
                        .WithMany("HistoricoList")
                        .HasForeignKey("EstudianteId");

                    b.HasOne("SeguimientoEnCasa.App.Dominio.SugerenciaEstudio", "SugerenciaEstudio")
                        .WithMany()
                        .HasForeignKey("SugerenciaEstudioId");

                    b.Navigation("SugerenciaEstudio");
                });

            modelBuilder.Entity("SeguimientoEnCasa.App.Dominio.Acudiente", b =>
                {
                    b.HasOne("SeguimientoEnCasa.App.Dominio.Estudiante", null)
                        .WithMany("AcudienteList")
                        .HasForeignKey("EstudianteId");
                });

            modelBuilder.Entity("SeguimientoEnCasa.App.Dominio.Maestro", b =>
                {
                    b.HasOne("SeguimientoEnCasa.App.Dominio.Estudiante", null)
                        .WithMany("MaestroList")
                        .HasForeignKey("EstudianteId");
                });

            modelBuilder.Entity("SeguimientoEnCasa.App.Dominio.Tutor", b =>
                {
                    b.HasOne("SeguimientoEnCasa.App.Dominio.Estudiante", null)
                        .WithMany("TutorList")
                        .HasForeignKey("EstudianteId");
                });

            modelBuilder.Entity("SeguimientoEnCasa.App.Dominio.Estudiante", b =>
                {
                    b.Navigation("AcudienteList");

                    b.Navigation("HistoricoList");

                    b.Navigation("MaestroList");

                    b.Navigation("TutorList");
                });
#pragma warning restore 612, 618
        }
    }
}
